Repository TagStudioDev/TagStudio, pull requests merged in 2024-06, with the labels that each got.

#233 Fix Raw Image Handling and Improve Text File Encoding Compatibility
  requirements.txt
  tagstudio/src/core/library.py
  tagstudio/src/core/utils/encoding.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: bug, refactor

#238 Bugfix for recent library re-creating a library at the last library location.
  tagstudio/src/core/enums.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/preview_panel.py
Labels: bug

#240 Bugfix Open Library Dialog
  tagstudio/src/qt/ts_qt.py
Labels: bug

#232 Multi mode search system
  tagstudio/src/core/enums.py
  tagstudio/src/core/library.py
  tagstudio/src/qt/main_window.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/ui/home.ui
  tagstudio/src/qt/ui/home_ui.py
Labels: enhancement, quality of life, UI/UX

#245 Fix Default Ignored File Extension
  tagstudio/src/core/library.py
  tagstudio/src/qt/modals/file_extension.py
Labels: bug

#231 Added various file formats to constants.py
  tagstudio/src/core/constants.py
Labels: enhancement

#255 Workflows: attempt fix for mismatched hashes in pip and bump MacOS version
  .github/workflows/apprun.yaml
  .github/workflows/mypy.yaml
  .github/workflows/release.yml
Labels: CI

#251 Add option to use a allowed extensions instead of ignored extensions
  tagstudio/src/core/json_typing.py
  tagstudio/src/core/library.py
  tagstudio/src/qt/modals/file_extension.py
  tagstudio/src/qt/ts_qt.py
Labels: Type: Enhancement

#259 Add "Clear Selection" button
  tagstudio/src/qt/ts_qt.py
Labels: Type: Enhancement, Type: QoL, Status: Review Needed

#258 Add Landing Page When No Library Is Opened
  tagstudio/resources/qt/images/tagstudio_logo_text_mono.png
  tagstudio/src/qt/helpers/color_overlay.py
  tagstudio/src/qt/helpers/gradient.py
  tagstudio/src/qt/main_window.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/clickable_label.py
  tagstudio/src/qt/widgets/landing.py
Labels: Type: QoL, Type: UI/UX

#244 Separately pin QT nixpkg version
  flake.lock
  flake.nix
Labels: Type: Installation, Priority: Medium, Status: Mergeable

#275 Bugfix for #252, don't attempt to read video file if invalid or 0 frames long
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: Type: Bug

#277 Use bug report and feature request forms for issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Type: Enhancement, Type: CI, Status: Mergeable

#279 Toggle Mouse Event Transparency on ItemThumbs (Fix #256)
  tagstudio/src/qt/widgets/item_thumb.py
Labels: Type: Bug, Type: UI/UX, Priority: High, Status: Mergeable

#274 Refactor `video_player.py` (Fix #270)
  tagstudio/resources/qt/images/pause.svg
  tagstudio/resources/qt/images/play.svg
  tagstudio/resources/qt/images/volume.svg
  tagstudio/resources/qt/images/volume_mute.svg
  tagstudio/src/qt/resource_manager.py
  tagstudio/src/qt/resources.json
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/video_player.py
Labels: Type: Bug, Type: Refactor, Type: UI/UX, Priority: High, Status: Review Needed

#153 Drag and drop files in and out of TagStudio
  tagstudio/src/qt/modals/drop_import.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/item_thumb.py
Labels: Type: Enhancement

#286 add tests into CI
  .github/workflows/pytest.yaml
  pyproject.toml
  requirements-dev.txt
  tagstudio/src/core/library.py
  tagstudio/tests/conftest.py
  tagstudio/tests/core/__snapshots__/test_lib/test_library_search[--nomatch--].json
  tagstudio/tests/core/__snapshots__/test_lib/test_library_search[First].json
  tagstudio/tests/core/__snapshots__/test_lib/test_library_search[Second].json
  tagstudio/tests/core/__snapshots__/test_lib/test_open_library.json
  tagstudio/tests/core/test_lib.py
  tagstudio/tests/core/test_tags.py
  tagstudio/tests/fixtures/library/.TagStudio/ts_library.json
  tagstudio/tests/fixtures/library/bar.txt
  tagstudio/tests/fixtures/library/foo.txt
Labels: Type: Tests, Type: CI, Priority: High

#289 fix: backslashes in f-string error on file drop dupe widget
  tagstudio/src/qt/modals/drop_import.py
Labels: Type: Bug, Priority: High

#292 create testing library files ad-hoc
  .gitignore
  tagstudio/tests/conftest.py
  tagstudio/tests/fixtures/library/bar.txt
  tagstudio/tests/fixtures/library/foo.txt
Labels: Type: Tests

#291 docs: Fixed outdated link to markdown file.
  README.md
Labels: Type: Documentation, Status: Mergeable

#157 refactoring: centralize field IDs
  tagstudio/src/core/constants.py
  tagstudio/src/core/enums.py
  tagstudio/src/core/library.py
  tagstudio/src/core/ts_core.py
  tagstudio/src/qt/modals/folders_to_tags.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/tag_box.py
Labels: Type: Refactor

#223 Update to pyside6 version 6.7.1
  .github/workflows/mypy.yaml
  requirements.txt
  tagstudio/src/qt/helpers/qbutton_wrapper.py
  tagstudio/src/qt/modals/add_field.py
  tagstudio/src/qt/pagination.py
  tagstudio/src/qt/widgets/fields.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/thumb_button.py
Labels: Type: Bug, Priority: Critical, Type: Refactor
