Repository TagStudioDev/TagStudio, pull requests merged in 2024-05, with the labels that each got.

#99 added action to close a library
  tagstudio/src/qt/ts_qt.py
Labels: enhancement

#103 show all tags in Add Tags panel by default
  tagstudio/src/core/library.py
  tagstudio/src/qt/modals/tag_search.py
Labels: enhancement

#126 Refactor strip_web_protocol()
  tagstudio/src/core/utils/web.py
Labels: refactor

#114 Remove functionally duplicated code in update_tags
  tagstudio/src/qt/modals/tag_database.py
Labels: refactor

#113 minor bug fixes to Tag Search Box
  tagstudio/src/qt/modals/tag_search.py
  tagstudio/src/qt/widgets/tag_box.py
Labels: quality of life

#111 feat: add hand cursor for active sidebar elements
  tagstudio/src/qt/widgets/preview_panel.py
Labels: enhancement, quality of life

#78 Build Script for windows
  .gitignore
  Build_win.bat
  requirements.txt
Labels: install/build tool

#141 Refactor: Deduplication in pagination.py's "Set Elipses Sizes" section
  tagstudio/src/qt/pagination.py
Labels: refactor

#76 Add Build Script for mac os systems
  .gitignore
  Build_MacOS_app.sh
Labels: install/build tool

#135 misc: remove duplicate code for tags updating
  tagstudio/src/qt/widgets/item_thumb.py
Labels: refactor

#165 ci: try to run the app
  .github/workflows/apprun.yaml
  requirements-dev.txt
  requirements.txt
  tagstudio/src/qt/ts_qt.py
  tagstudio/tag_studio.py
Labels: tests

#151 add list of libraries into sidebar
  tagstudio/src/core/enums.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/preview_panel.py
Labels: enhancement, UI/UX

#161 ci: add mypy check
  .github/workflows/mypy.yaml
  pyproject.toml
  requirements-dev.txt
  tagstudio/src/cli/ts_cli.py
  tagstudio/src/core/field_template.py
  tagstudio/src/core/json_typing.py
  tagstudio/src/core/library.py
  tagstudio/src/core/palette.py
  tagstudio/src/core/ts_core.py
  tagstudio/src/qt/helpers/function_iterator.py
  tagstudio/src/qt/modals/folders_to_tags.py
  tagstudio/src/qt/modals/mirror_entities.py
  tagstudio/src/qt/pagination.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/collage_icon.py
  tagstudio/src/qt/widgets/fields.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/panel.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/tag_box.py
  tagstudio/src/qt/widgets/thumb_button.py
  tagstudio/src/qt/widgets/thumb_renderer.py
  tagstudio/tag_studio.py
Labels: tests

#142 Add pytest support
  README.md
  requirements-dev.txt
  tagstudio/src/core/constants.py
  tagstudio/src/core/library.py
  tagstudio/src/core/ts_core.py
  tagstudio/src/qt/modals/build_tag.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/collage_icon.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/thumb_renderer.py
  tagstudio/tests/core/test_tags.py
Labels: enhancement, refactor, tests

#194 Wiki/Docs Updates
  doc/Entry.md
  doc/Field.md
  doc/Home.md
  doc/Library.md
  doc/Macro.md
  doc/Tag.md
  doc/documentation.md
Labels: documentation

#217 feat: add select all hotkey
  tagstudio/src/qt/ts_qt.py
Labels: enhancement, quality of life

#156 Replace use of os.path with pathlib
  tagstudio/src/cli/ts_cli.py
  tagstudio/src/core/constants.py
  tagstudio/src/core/library.py
  tagstudio/src/core/ts_core.py
  tagstudio/src/qt/helpers/file_opener.py
  tagstudio/src/qt/main_window.py
  tagstudio/src/qt/modals/delete_unlinked.py
  tagstudio/src/qt/modals/fix_dupes.py
  tagstudio/src/qt/modals/folders_to_tags.py
  tagstudio/src/qt/pagination.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/ui/home_ui.py
  tagstudio/src/qt/widgets/collage_icon.py
  tagstudio/src/qt/widgets/fields.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/tag.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: refactor

#149 Video Player
  .github/workflows/apprun.yaml
  tagstudio/resources/pause.svg
  tagstudio/resources/play.svg
  tagstudio/resources/volume_muted.svg
  tagstudio/resources/volume_unmuted.svg
  tagstudio/src/core/enums.py
  tagstudio/src/qt/resources_rc.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/video_player.py
Labels: enhancement

#228 Fix rawpy- and filepermissionerror
  tagstudio/src/core/library.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: bug
