Repository TagStudioDev/TagStudio, pull requests merged in 2024-10, with the labels that each got.

#530 Translations update from Hosted Weblate
  tagstudio/resources/translations/da.json
  tagstudio/resources/translations/de.json
  tagstudio/resources/translations/en.json
  tagstudio/resources/translations/es.json
  tagstudio/resources/translations/fr.json
  tagstudio/resources/translations/hu.json
  tagstudio/resources/translations/it.json
  tagstudio/resources/translations/nb_NO.json
  tagstudio/resources/translations/pt.json
  tagstudio/resources/translations/pt_BR.json
  tagstudio/resources/translations/ru.json
  tagstudio/resources/translations/sv.json
  tagstudio/resources/translations/ta.json
  tagstudio/resources/translations/tok.json
  tagstudio/resources/translations/tr.json
  tagstudio/resources/translations/yue_Hant.json
Labels: Type: Translation

#503 feat: store `Entry` suffix separately
  tagstudio/src/core/constants.py
  tagstudio/src/core/driver.py
  tagstudio/src/core/enums.py
  tagstudio/src/core/library/alchemy/fields.py
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/core/library/alchemy/models.py
  tagstudio/src/core/library/json/library.py
  tagstudio/src/qt/modals/file_extension.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/video_player.py
  tagstudio/tests/conftest.py
  tagstudio/tests/macros/test_refresh_dir.py
  tagstudio/tests/qt/test_qt_driver.py
  tagstudio/tests/test_driver.py
  tagstudio/tests/test_library.py
Labels: Type: Refactor, TagStudio: Library, Status: Mergeable

#522 feat: port thumbnail (#390) and related features to v9.5
  .gitignore
  .vscode/launch.json
  pyproject.toml
  requirements.txt
  tagstudio/resources/qt/images/broken_link_icon.png
  tagstudio/resources/qt/images/file_icons/adobe_illustrator.png
  tagstudio/resources/qt/images/file_icons/adobe_photoshop.png
  tagstudio/resources/qt/images/file_icons/affinity_photo.png
  tagstudio/resources/qt/images/file_icons/audio.png
  tagstudio/resources/qt/images/file_icons/document.png
  tagstudio/resources/qt/images/file_icons/file_generic.png
  tagstudio/resources/qt/images/file_icons/font.png
  tagstudio/resources/qt/images/file_icons/image.png
  tagstudio/resources/qt/images/file_icons/image_vector.png
  tagstudio/resources/qt/images/file_icons/material.png
  tagstudio/resources/qt/images/file_icons/model.png
  tagstudio/resources/qt/images/file_icons/presentation.png
  tagstudio/resources/qt/images/file_icons/program.png
  tagstudio/resources/qt/images/file_icons/spreadsheet.png
  tagstudio/resources/qt/images/file_icons/text.png
  tagstudio/resources/qt/images/file_icons/video.png
  tagstudio/resources/qt/images/thumb_border_512.png
  tagstudio/resources/qt/images/thumb_broken_512.png
  tagstudio/resources/qt/images/thumb_file_default_512.png
  tagstudio/resources/qt/images/thumb_loading.png
  tagstudio/resources/qt/images/thumb_loading_512.png
  tagstudio/resources/qt/images/thumb_loading_dark_512.png
  tagstudio/resources/qt/images/thumb_mask_128.png
  tagstudio/resources/qt/images/thumb_mask_512.png
  tagstudio/resources/qt/images/thumb_mask_hl_512.png
  tagstudio/src/core/constants.py
  tagstudio/src/core/enums.py
  tagstudio/src/core/media_types.py
  tagstudio/src/core/palette.py
  tagstudio/src/qt/helpers/blender_thumbnailer.py
  tagstudio/src/qt/helpers/color_overlay.py
  tagstudio/src/qt/helpers/file_tester.py
  tagstudio/src/qt/helpers/gradient.py
  tagstudio/src/qt/helpers/rounded_pixmap_style.py
  tagstudio/src/qt/helpers/silent_popen.py
  tagstudio/src/qt/helpers/text_wrapper.py
  tagstudio/src/qt/helpers/vendored/ffmpeg.py
  tagstudio/src/qt/helpers/vendored/pydub/audio_segment.py
  tagstudio/src/qt/helpers/vendored/pydub/utils.py
  tagstudio/src/qt/main_window.py
  tagstudio/src/qt/platform_strings.py
  tagstudio/src/qt/resource_manager.py
  tagstudio/src/qt/resources.json
  tagstudio/src/qt/resources_rc.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/collage_icon.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/thumb_button.py
  tagstudio/src/qt/widgets/thumb_renderer.py
  tagstudio/src/qt/widgets/video_player.py
  tagstudio/tests/qt/test_preview_panel.py
Labels: Type: Enhancement, Type: UI/UX, Priority: Medium, Status: Mergeable

#536 fix: dont check db version with new library
  tagstudio/src/core/library/alchemy/library.py
Labels: Type: Bug, Priority: Critical

#520 fix running mypy from project directory
  pyproject.toml
Labels: Type: CI, Priority: High, Status: Mergeable

#544 ci: pin pytest ubuntu version to 22.04
  .github/workflows/pytest.yaml
Labels: Type: CI, Priority: High, Status: Review Needed

#540 feat: add svg thumbnail support (port #442)
  tagstudio/src/qt/widgets/thumb_renderer.py
  tagstudio/tests/fixtures/sample.svg
  tagstudio/tests/qt/__snapshots__/test_thumb_renderer/test_svg_preview.png
  tagstudio/tests/qt/test_thumb_renderer.py
Labels: Type: Enhancement, Type: UI/UX, Priority: Low, Status: Review Needed

#543 feat: add pdf thumbnail support (port #378)
  tagstudio/src/qt/helpers/image_effects.py
  tagstudio/src/qt/widgets/thumb_renderer.py
  tagstudio/tests/fixtures/sample.pdf
  tagstudio/tests/qt/__snapshots__/test_thumb_renderer/test_pdf_preview.png
  tagstudio/tests/qt/test_thumb_renderer.py
Labels: Type: Enhancement, Type: UI/UX, Priority: Low, Status: Review Needed

#539 feat: add ePub thumbnail support (port #387)
  tagstudio/src/core/media_types.py
  tagstudio/src/qt/widgets/thumb_renderer.py
  tagstudio/tests/fixtures/sample.epub
  tagstudio/tests/qt/__snapshots__/test_thumb_renderer/test_epub_preview.png
  tagstudio/tests/qt/test_thumb_renderer.py
Labels: Type: Enhancement, Type: UI/UX, Priority: Low, Status: Review Needed

#564 fix: Corrected link to lead to the roadmap.
  README.md
Labels: Type: Bug, Type: Documentation
