Repository TagStudioDev/TagStudio, pull requests merged in 2024-07, with the labels that each got.

#273 Blender thumbnail support
  tagstudio/src/core/constants.py
  tagstudio/src/qt/helpers/blender_thumbnailer.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: Type: Enhancement, Type: QoL, Type: UI/UX, Priority: Low, Status: Mergeable

#306 Fixes Bug #305
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Bug

#134 use list widget for selecting fields to add
  tagstudio/src/qt/modals/add_field.py
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Enhancement

#79 Copy and Paste + Shortcuts
  tagstudio/src/qt/ts_qt.py
Labels: Type: Enhancement

#307 Add font thumbnail preview support
  tagstudio/src/core/constants.py
  tagstudio/src/qt/helpers/text_wrapper.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: Type: Enhancement, Type: UI/UX, Status: Mergeable

#329 feat(ui): sort tags in add tag panel by color/alphabetical (close #327)
  tagstudio/src/qt/modals/tag_database.py
  tagstudio/src/qt/modals/tag_search.py
Labels: Type: Enhancement, Type: UI/UX, TagStudio: Tags, TagStudio: Search
