Repository TagStudioDev/TagStudio, pull requests merged in 2024-11, with the labels that each got.

#554 [9.4.x] Create auto-backup of library for use in save failures (Fix #343)
  tagstudio/src/core/library.py
Labels: Priority: Critical, TagStudio: Library, Type: File System

#551 fix resolution info #550
  tagstudio/src/core/media_types.py
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Bug, Type: UI/UX, Status: Mergeable

#579 Translations update from Hosted Weblate
  tagstudio/resources/translations/da.json
  tagstudio/resources/translations/de.json
  tagstudio/resources/translations/en.json
  tagstudio/resources/translations/es.json
  tagstudio/resources/translations/fr.json
  tagstudio/resources/translations/hu.json
  tagstudio/resources/translations/it.json
  tagstudio/resources/translations/nb_NO.json
  tagstudio/resources/translations/pt.json
  tagstudio/resources/translations/pt_BR.json
  tagstudio/resources/translations/ru.json
  tagstudio/resources/translations/sv.json
  tagstudio/resources/translations/ta.json
  tagstudio/resources/translations/tok.json
  tagstudio/resources/translations/tr.json
  tagstudio/resources/translations/yue_Hant.json
Labels: Type: Translation

#545 feat: add OpenDocument thumbnail support (port #366)
  tagstudio/src/core/media_types.py
  tagstudio/src/qt/widgets/thumb_renderer.py
  tagstudio/tests/fixtures/sample.ods
  tagstudio/tests/fixtures/sample.odt
  tagstudio/tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.epub-_epub_cover].png
  tagstudio/tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.ods-_open_doc_thumb].png
  tagstudio/tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.odt-_open_doc_thumb].png
  tagstudio/tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.pdf-thumbnailer3].png
  tagstudio/tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.svg-thumbnailer4].png
  tagstudio/tests/qt/test_thumb_renderer.py
Labels: Type: Enhancement, Type: UI/UX, Priority: Low, Status: Mergeable

#549 feat: add JXL thumbnail and animated APNG + WEBP support (port #344 and #357)
  requirements.txt
  tagstudio/src/core/media_types.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: Type: Enhancement, Type: UI/UX, Priority: Low

#581 docs: update CONTRIBUTING.md ruff instructions
  CONTRIBUTING.md
Labels: Type: Documentation

#575 feat: add filetype and mediatype searches
  tagstudio/src/core/library/alchemy/enums.py
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/core/media_types.py
  tagstudio/tests/conftest.py
  tagstudio/tests/test_library.py
Labels: Priority: High, TagStudio: Search

#582 feat: make path search use globs
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/tests/qt/test_qt_driver.py
  tagstudio/tests/test_library.py
Labels: Type: Enhancement, Status: Mergeable, TagStudio: Search

#583 remove queued thumnail jobs when closing library
  tagstudio/src/qt/ts_qt.py
Labels: Type: Bug, Type: UI/UX, Priority: High

#594 docs: fix link to the feature roadmap page
  CONTRIBUTING.md
  README.md
  docs/index.md
  docs/updates/roadmap.md
  mkdocs.yml
Labels: Type: Bug, Type: Documentation

#586 feat: add autocomplete for search engine
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/qt/main_window.py
  tagstudio/src/qt/ts_qt.py
Labels: Type: Enhancement, Type: QoL, Priority: Medium, Status: Mergeable, TagStudio: Search

#560 [fix] bug where preview panel ui would not update when fields where removed from an entry
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Bug, Type: UI/UX

#592 feat: Make the create tag panel have empty tag name field
  tagstudio/src/qt/modals/build_tag.py
  tagstudio/src/qt/widgets/panel.py
  tagstudio/src/qt/widgets/tag_box.py
Labels: Type: QoL, Type: UI/UX, Priority: Low, TagStudio: Tags

#596 feat(parity): backend for aliases and parent tags
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/core/library/alchemy/models.py
  tagstudio/src/qt/flowlayout.py
  tagstudio/src/qt/modals/build_tag.py
  tagstudio/src/qt/modals/tag_database.py
  tagstudio/src/qt/modals/tag_search.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/tag.py
  tagstudio/src/qt/widgets/tag_box.py
  tagstudio/tests/qt/test_build_tag_panel.py
  tagstudio/tests/qt/test_tag_widget.py
  tagstudio/tests/test_library.py
Labels: Type: Enhancement, TagStudio: Library, Priority: High, TagStudio: Tags

#609 fix: shut up mypy
  tagstudio/src/qt/helpers/file_opener.py
  tagstudio/src/qt/ts_qt.py
Labels: Type: Bug, Type: QoL, Type: CI, Priority: Medium, Status: Mergeable, System: Windows, System: macOS

#603 Fixed open in explorer does not open the correct folder
  tagstudio/src/qt/helpers/file_opener.py
Labels: Type: Bug, TagStudio: Library, Priority: Medium, Status: Mergeable, Type: File System

#576 feat: Audio Playback
  tagstudio/src/qt/widgets/media_player.py
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Enhancement, Type: UI/UX, Priority: Medium, Status: Mergeable

#604 feat(parity): migrate json libraries to sqlite
  .gitignore
  tagstudio/src/core/library/alchemy/enums.py
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/core/library/alchemy/models.py
  tagstudio/src/core/library/json/library.py
  tagstudio/src/qt/modals/tag_database.py
  tagstudio/src/qt/modals/tag_search.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/migration_modal.py
  tagstudio/src/qt/widgets/paged_panel/paged_body_wrapper.py
  tagstudio/src/qt/widgets/paged_panel/paged_panel.py
  tagstudio/src/qt/widgets/paged_panel/paged_panel_state.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/tag_box.py
  tagstudio/tests/fixtures/json_library/.TagStudio/ts_library.json
  tagstudio/tests/test_json_migration.py
  tagstudio/tests/test_library.py
Labels: Type: Enhancement, Type: QoL, TagStudio: Library, Priority: High

#613 Small fix: Remove unnecessary warning in console
  tagstudio/src/qt/widgets/fields.py
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Bug, Priority: Low
