Repository TagStudioDev/TagStudio, pull requests merged in 2024-09, with the labels that each got.

#373 Add support for VALVe Source 1 + 2 files
  requirements.txt
  tagstudio/src/core/media_types.py
  tagstudio/src/core/palette.py
  tagstudio/src/qt/widgets/fields.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: Type: Enhancement, Type: UI/UX, Status: Mergeable

#403 Sidecar macro fixes
  tagstudio/src/core/library.py
  tagstudio/src/core/ts_core.py
  tagstudio/src/qt/ts_qt.py
Labels: Type: Enhancement, TagStudio: Library, Priority: Low, Status: Mergeable

#409 feat: expanded file deletion/trashing
  requirements.txt
  tagstudio/resources/qt/videos/placeholder.mp4
  tagstudio/src/core/media_types.py
  tagstudio/src/qt/helpers/file_deleter.py
  tagstudio/src/qt/resource_manager.py
  tagstudio/src/qt/resources.json
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/fields.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Enhancement, Type: Refactor, Type: QoL, Type: UI/UX, Priority: Medium, Type: File System

#425 Postpone instantiating modal windows
  tagstudio/src/qt/ts_qt.py
Labels: Type: QoL, Type: UI/UX, Priority: Medium

#430 feat(ui): show file creation/modified dates + restyle path label
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Enhancement, Type: QoL, Type: UI/UX

#436 fix: Do not create command prompt window on subprocess
  pyproject.toml
  tagstudio/src/qt/helpers/file_tester.py
  tagstudio/src/qt/helpers/silent_popen.py
  tagstudio/src/qt/helpers/vendored/ffmpeg.py
  tagstudio/src/qt/helpers/vendored/pydub/audio_segment.py
  tagstudio/src/qt/helpers/vendored/pydub/utils.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: Type: Bug, Priority: Critical

#467 Update site_url in mkdocs.yml
  mkdocs.yml
Labels: Type: Bug, Type: CI

#472 fix(PreviewPanel): Use birthtime for creation time on Mac & Windows
  tagstudio/src/qt/widgets/preview_panel.py
Labels: Type: Bug, Type: File System, System: Windows, System: macOS

#471 fix(ThumbRenderer): Use audio icon when no ffmpeg
  tagstudio/src/qt/helpers/vendored/pydub/audio_segment.py
  tagstudio/src/qt/widgets/thumb_renderer.py
Labels: Type: Bug, Type: UI/UX, Priority: Medium

#452 fix small grammar mistake in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type: Documentation

#474 Add discord server link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type: Documentation

#473 docs: Add ffmpeg installation guide
  docs/help/ffmpeg.md
Labels: Type: Documentation, Status: Mergeable

#478 fix(Flake): Add missing x11 dependency
  flake.nix
Labels: Type: Bug, Type: Installation, Status: Review Needed, System: Linux

#484 fix error on closing library
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/tests/conftest.py
  tagstudio/tests/qt/test_driver.py
Labels: Type: Bug, TagStudio: Library

#483 fix(QtDriver): Retain filter on directory refresh
  tagstudio/src/qt/ts_qt.py
Labels: Type: Bug, TagStudio: Search

#486 feat: increase file scanning performance
  tagstudio/src/core/library.py
  tagstudio/src/qt/modals/drop_import.py
Labels: Type: QoL, Priority: Medium, Type: File System

#494 cleanup the `refresh_dir` code, update tests
  .github/workflows/mypy.yaml
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/core/utils/refresh_dir.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/tests/conftest.py
  tagstudio/tests/macros/test_dupe_entries.py
  tagstudio/tests/macros/test_refresh_dir.py
  tagstudio/tests/qt/test_preview_panel.py
Labels: Type: Tests, TagStudio: Library, Type: CI, Type: File System

#481 Fix tag search to not require wildcards
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/tests/test_library.py
Labels: Type: QoL, Priority: Medium, TagStudio: Tags, TagStudio: Search

#498 feat: make search results more ergonomic
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/core/utils/dupe_files.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/tests/macros/test_missing_files.py
  tagstudio/tests/test_library.py
Labels: Type: Refactor, TagStudio: Library, Priority: High

#441 feat: Warn user if FFmpeg is not installed
  .github/workflows/apprun.yaml
  tagstudio/src/qt/modals/ffmpeg_checker.py
  tagstudio/src/qt/ts_qt.py
Labels: Type: UI/UX, Priority: Medium

#496 Fixed small Typo in a Comment in test_driver.py
  tagstudio/tests/qt/test_driver.py
Labels: Priority: Low

#507 Add en.json with strings found in code
  tagstudio/resources/translations/en.json
Labels: Type: Translation, Status: Mergeable

#526 Translations update from Hosted Weblate
  .git-blame-ignore-revs
  tagstudio/resources/translations/da.json
  tagstudio/resources/translations/de.json
  tagstudio/resources/translations/en.json
  tagstudio/resources/translations/es.json
  tagstudio/resources/translations/fr.json
  tagstudio/resources/translations/hu.json
  tagstudio/resources/translations/it.json
  tagstudio/resources/translations/nb_NO.json
  tagstudio/resources/translations/pt.json
  tagstudio/resources/translations/pt_BR.json
  tagstudio/resources/translations/ru.json
  tagstudio/resources/translations/sv.json
  tagstudio/resources/translations/ta.json
  tagstudio/resources/translations/tok.json
  tagstudio/resources/translations/tr.json
Labels: Type: Translation, Priority: Medium
