Repository TagStudioDev/TagStudio, pull requests merged in 2025-08, with the labels that each got.

#952 refactor(preview_panel): mvc split
  pyproject.toml
  src/tagstudio/core/library/alchemy/library.py
  src/tagstudio/qt/controller/widgets/preview_panel_controller.py
  src/tagstudio/qt/main_window.py
  src/tagstudio/qt/modals/build_tag.py
  src/tagstudio/qt/modals/folders_to_tags.py
  src/tagstudio/qt/modals/mirror_entities.py
  src/tagstudio/qt/modals/settings_panel.py
  src/tagstudio/qt/modals/tag_color_manager.py
  src/tagstudio/qt/modals/tag_search.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/view/widgets/preview_panel_view.py
  src/tagstudio/qt/widgets/item_thumb.py
  src/tagstudio/qt/widgets/preview_panel.py
  src/tagstudio/qt/widgets/tag_box.py
  tests/qt/test_field_containers.py
  tests/qt/test_file_path_options.py
  tests/qt/test_preview_panel.py
Labels: Type: Refactor

#978 refactor(preview_thumb): mvc split
  STYLE.md
  src/tagstudio/core/media_types.py
  src/tagstudio/qt/controller/widgets/preview/preview_thumb_controller.py
  src/tagstudio/qt/controller/widgets/preview_panel_controller.py
  src/tagstudio/qt/helpers/qbutton_wrapper.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/view/widgets/preview/preview_thumb_view.py
  src/tagstudio/qt/view/widgets/preview_panel_view.py
  src/tagstudio/qt/widgets/preview/file_attributes.py
  src/tagstudio/qt/widgets/preview/preview_thumb.py
Labels: Type: Refactor, Status: Blocked

#974 closes: #973 Completes traditional chinese translations
  src/tagstudio/resources/translations/zh_Hant.json
Labels: Type: Translations

#956 feat: zoom keyboard shortcut
  src/tagstudio/qt/main_window.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/resources/translations/en.json
Labels: Type: Enhancement, Type: QoL, Type: UI/UX

#957 Improve main_window.py
  src/tagstudio/qt/main_window.py
Labels: Type: Refactor, Status: Review Needed

#1006 fix(library): get_tag_by_name
  src/tagstudio/core/library/alchemy/library.py
Labels: Type: Bug, TagStudio: Library, TagStudio: Search

#1008 fix: ensure initial browsing state uses UI values
  src/tagstudio/qt/ts_qt.py
Labels: Type: Bug, Type: UI/UX, Priority: Medium

#1005 fix: preview thumbnails don't scale as large as they could
  src/tagstudio/qt/view/widgets/preview/preview_thumb_view.py
Labels: Type: Bug, Type: UI/UX, Priority: Medium

#1003 refactor(tag_box): mvc split
  src/tagstudio/qt/controller/components/tag_box_controller.py
  src/tagstudio/qt/view/components/tag_box_view.py
  src/tagstudio/qt/widgets/preview/field_containers.py
  src/tagstudio/qt/widgets/tag_box.py
Labels: Type: Refactor

#924 feat: clickable links in text fields
  src/tagstudio/qt/widgets/text.py
Labels: Type: Enhancement, Type: QoL, Type: UI/UX, Status: Mergeable

#1025 ui: tweak media player style and behavior
  src/tagstudio/qt/helpers/qslider_wrapper.py
  src/tagstudio/qt/view/widgets/preview/preview_thumb_view.py
  src/tagstudio/qt/widgets/media_player.py
Labels: Type: QoL, Type: UI/UX

#1027 fix: folders with names of unlinked entries are linked
  src/tagstudio/core/utils/missing_files.py
  src/tagstudio/qt/controller/widgets/preview/preview_thumb_controller.py
  src/tagstudio/qt/helpers/file_deleter.py
  src/tagstudio/qt/helpers/file_opener.py
  src/tagstudio/qt/widgets/preview/file_attributes.py
  src/tagstudio/qt/widgets/thumb_renderer.py
Labels: Type: Bug, TagStudio: Library

#1060 feat: cli version argument
  src/tagstudio/main.py
Labels: Type: Enhancement, Type: QoL, Type: Installation

#1057 feat: add settings to disable automatic thumbnail generation for sound
  src/tagstudio/core/global_settings.py
  src/tagstudio/qt/modals/settings_panel.py
  src/tagstudio/qt/view/widgets/preview/preview_thumb_view.py
  src/tagstudio/qt/widgets/item_thumb.py
  src/tagstudio/qt/widgets/thumb_renderer.py
  src/tagstudio/resources/translations/en.json
Labels: Type: QoL, Type: UI/UX, TagStudio: Library

#1039 refactor: make cache_manager thread safe
  src/tagstudio/qt/cache_manager.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/view/widgets/preview/preview_thumb_view.py
  src/tagstudio/qt/widgets/item_thumb.py
  src/tagstudio/qt/widgets/thumb_renderer.py
Labels: Type: Refactor, TagStudio: Library

#942 perf: Optimize db queries for preview panel
  src/tagstudio/core/library/alchemy/library.py
  src/tagstudio/core/library/alchemy/models.py
  src/tagstudio/qt/controller/components/tag_box_controller.py
  src/tagstudio/qt/modals/tag_database.py
  src/tagstudio/qt/modals/tag_search.py
  src/tagstudio/qt/view/components/tag_box_view.py
  src/tagstudio/qt/widgets/preview/field_containers.py
  src/tagstudio/qt/widgets/tag.py
Labels: Status: Mergeable, TagStudio: Search, Type: Performance

#1046 feat: replace extension exclusion system with `.ts_ignore`
  src/tagstudio/core/library/alchemy/library.py
  src/tagstudio/core/library/ignore.py
  src/tagstudio/qt/controller/widgets/ignore_modal_controller.py
  src/tagstudio/qt/main_window.py
  src/tagstudio/qt/modals/file_extension.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/view/widgets/ignore_modal_view.py
  src/tagstudio/qt/widgets/preview/file_attributes.py
  src/tagstudio/qt/widgets/thumb_renderer.py
  src/tagstudio/resources/templates/ts_ignore_template.txt
  src/tagstudio/resources/templates/ts_ignore_template_blank.txt
  src/tagstudio/resources/translations/de.json
  src/tagstudio/resources/translations/en.json
  src/tagstudio/resources/translations/es.json
  src/tagstudio/resources/translations/fil.json
  src/tagstudio/resources/translations/fr.json
  src/tagstudio/resources/translations/hu.json
  src/tagstudio/resources/translations/ja.json
  src/tagstudio/resources/translations/nb_NO.json
  src/tagstudio/resources/translations/nl.json
  src/tagstudio/resources/translations/pl.json
  src/tagstudio/resources/translations/pt.json
  src/tagstudio/resources/translations/pt_BR.json
  src/tagstudio/resources/translations/qpv.json
  src/tagstudio/resources/translations/ru.json
  src/tagstudio/resources/translations/sv.json
  src/tagstudio/resources/translations/ta.json
  src/tagstudio/resources/translations/tok.json
  src/tagstudio/resources/translations/tr.json
  src/tagstudio/resources/translations/zh_Hans.json
  src/tagstudio/resources/translations/zh_Hant.json
  tests/qt/test_file_path_options.py
  tests/test_library.py
  tests/test_search.py
Labels: Type: Enhancement, Type: Refactor, TagStudio: Library, Priority: High, TagStudio: Search

#1065 chore(thumb_renderer): prepare for pillow_heif removing AVIF support
  nix/package/default.nix
  pyproject.toml
  src/tagstudio/qt/widgets/thumb_renderer.py
Labels: Type: Installation, Type: UI/UX, Priority: Low

#1075 fix: add loop cutoff to get_tag_categories()
  src/tagstudio/qt/widgets/preview/field_containers.py
Labels: Type: Bug, Priority: Critical, Type: UI/UX, TagStudio: Tags

#1070 feat: add library cleanup screen and 'fix ignored files' window
  src/tagstudio/core/library/alchemy/constants.py
  src/tagstudio/core/library/alchemy/library.py
  src/tagstudio/core/ts_core.py
  src/tagstudio/core/utils/ignored_registry.py
  src/tagstudio/core/utils/refresh_dir.py
  src/tagstudio/core/utils/unlinked_registry.py
  src/tagstudio/qt/controller/fix_ignored_modal_controller.py
  src/tagstudio/qt/controller/widgets/library_info_window_controller.py
  src/tagstudio/qt/main_window.py
  src/tagstudio/qt/modals/fix_dupes.py
  src/tagstudio/qt/modals/fix_unlinked.py
  src/tagstudio/qt/modals/mirror_entries_modal.py
  src/tagstudio/qt/modals/relink_entries_modal.py
  src/tagstudio/qt/modals/remove_ignored_modal.py
  src/tagstudio/qt/modals/remove_unlinked_modal.py
  src/tagstudio/qt/resources.json
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/view/widgets/fix_ignored_modal_view.py
  src/tagstudio/qt/view/widgets/library_info_window_view.py
  src/tagstudio/qt/widgets/thumb_renderer.py
  src/tagstudio/resources/qt/images/dupe_file_stat.png
  src/tagstudio/resources/qt/images/ignored_stat.png
  src/tagstudio/resources/qt/images/unlinked_stat.png
  src/tagstudio/resources/translations/de.json
  src/tagstudio/resources/translations/en.json
  src/tagstudio/resources/translations/es.json
  src/tagstudio/resources/translations/fil.json
  src/tagstudio/resources/translations/fr.json
  src/tagstudio/resources/translations/hu.json
  src/tagstudio/resources/translations/ja.json
  src/tagstudio/resources/translations/nb_NO.json
  src/tagstudio/resources/translations/pl.json
  src/tagstudio/resources/translations/pt.json
  src/tagstudio/resources/translations/pt_BR.json
  src/tagstudio/resources/translations/qpv.json
  src/tagstudio/resources/translations/ru.json
  src/tagstudio/resources/translations/sv.json
  src/tagstudio/resources/translations/ta.json
  src/tagstudio/resources/translations/tok.json
  src/tagstudio/resources/translations/tr.json
  src/tagstudio/resources/translations/zh_Hans.json
  src/tagstudio/resources/translations/zh_Hant.json
  tests/macros/test_missing_files.py
  tests/qt/test_resource_manager.py
  tests/test_db_migrations.py
Labels: Type: Enhancement, Type: Refactor, Type: QoL, Type: UI/UX, TagStudio: Library, Type: Translations, Priority: High
