Repository TagStudioDev/TagStudio, pull requests merged in 2025-03, with the labels that each got.

#817 fix: resouce leak in `translate_with_setter` by deleting the offending code
  tagstudio/src/core/library/alchemy/library.py
  tagstudio/src/qt/main_window.py
  tagstudio/src/qt/modals/about.py
  tagstudio/src/qt/modals/add_field.py
  tagstudio/src/qt/modals/build_color.py
  tagstudio/src/qt/modals/build_namespace.py
  tagstudio/src/qt/modals/build_tag.py
  tagstudio/src/qt/modals/delete_unlinked.py
  tagstudio/src/qt/modals/drop_import.py
  tagstudio/src/qt/modals/file_extension.py
  tagstudio/src/qt/modals/fix_dupes.py
  tagstudio/src/qt/modals/fix_unlinked.py
  tagstudio/src/qt/modals/folders_to_tags.py
  tagstudio/src/qt/modals/merge_dupe_entries.py
  tagstudio/src/qt/modals/mirror_entities.py
  tagstudio/src/qt/modals/relink_unlinked.py
  tagstudio/src/qt/modals/settings_panel.py
  tagstudio/src/qt/modals/tag_color_manager.py
  tagstudio/src/qt/modals/tag_color_selection.py
  tagstudio/src/qt/modals/tag_database.py
  tagstudio/src/qt/modals/tag_search.py
  tagstudio/src/qt/translations.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/color_box.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/landing.py
  tagstudio/src/qt/widgets/migration_modal.py
  tagstudio/src/qt/widgets/paged_panel/paged_panel_state.py
  tagstudio/src/qt/widgets/panel.py
  tagstudio/src/qt/widgets/preview/field_containers.py
  tagstudio/src/qt/widgets/preview/file_attributes.py
  tagstudio/src/qt/widgets/preview/preview_thumb.py
  tagstudio/src/qt/widgets/preview_panel.py
  tagstudio/src/qt/widgets/tag.py
  tagstudio/src/qt/widgets/tag_color_label.py
  tagstudio/src/qt/widgets/tag_color_preview.py
  tagstudio/src/qt/widgets/video_player.py
Labels: Type: Bug, Type: Refactor, Type: Translation, Priority: High

#809 Translations update from Hosted Weblate
  tagstudio/resources/translations/de.json
  tagstudio/resources/translations/es.json
  tagstudio/resources/translations/fil.json
  tagstudio/resources/translations/fr.json
  tagstudio/resources/translations/hu.json
  tagstudio/resources/translations/pl.json
  tagstudio/resources/translations/pt_BR.json
Labels: Type: Translation

#834 docs: correct spelling of Category
  README.md
Labels: Type: Bug, Type: Documentation

#830 fix: restore `translate_formatted()` method
  tagstudio/src/qt/modals/about.py
  tagstudio/src/qt/modals/delete_unlinked.py
  tagstudio/src/qt/modals/drop_import.py
  tagstudio/src/qt/modals/fix_dupes.py
  tagstudio/src/qt/modals/fix_unlinked.py
  tagstudio/src/qt/modals/mirror_entities.py
  tagstudio/src/qt/modals/relink_unlinked.py
  tagstudio/src/qt/modals/tag_database.py
  tagstudio/src/qt/modals/tag_search.py
  tagstudio/src/qt/translations.py
  tagstudio/src/qt/ts_qt.py
  tagstudio/src/qt/widgets/color_box.py
  tagstudio/src/qt/widgets/item_thumb.py
  tagstudio/src/qt/widgets/landing.py
  tagstudio/src/qt/widgets/migration_modal.py
  tagstudio/src/qt/widgets/preview/field_containers.py
  tagstudio/src/qt/widgets/preview/file_attributes.py
  tagstudio/src/qt/widgets/preview/preview_thumb.py
Labels: Type: Bug, Priority: Critical, Type: Refactor, Type: Translation

#826 Translations update from Hosted Weblate
  tagstudio/resources/translations/da.json
  tagstudio/resources/translations/de.json
  tagstudio/resources/translations/es.json
  tagstudio/resources/translations/fil.json
  tagstudio/resources/translations/fr.json
  tagstudio/resources/translations/nb_NO.json
  tagstudio/resources/translations/pl.json
  tagstudio/resources/translations/pt_BR.json
  tagstudio/resources/translations/ru.json
  tagstudio/resources/translations/sv.json
  tagstudio/resources/translations/ta.json
  tagstudio/resources/translations/tok.json
  tagstudio/resources/translations/tr.json
  tagstudio/resources/translations/zh_Hant.json
Labels: Type: Translation

#835 Translations update from Hosted Weblate
  tagstudio/resources/translations/da.json
  tagstudio/resources/translations/es.json
  tagstudio/resources/translations/fil.json
  tagstudio/resources/translations/nb_NO.json
  tagstudio/resources/translations/ta.json
  tagstudio/resources/translations/tok.json
  tagstudio/resources/translations/tr.json
Labels: Type: Bug, Type: Translation, Priority: High

#833 feat: add tests for translations
  tagstudio/tests/conftest.py
  tagstudio/tests/macros/test_dupe_entries.py
  tagstudio/tests/macros/test_missing_files.py
  tagstudio/tests/macros/test_refresh_dir.py
  tagstudio/tests/test_json_migration.py
  tagstudio/tests/test_translations.py
Labels: Type: Tests, Type: Translation, Priority: Medium

#836 fix: separate about screen title from translations
  tagstudio/resources/translations/de.json
  tagstudio/resources/translations/en.json
  tagstudio/resources/translations/es.json
  tagstudio/resources/translations/fil.json
  tagstudio/resources/translations/fr.json
  tagstudio/resources/translations/hu.json
  tagstudio/resources/translations/pt_BR.json
  tagstudio/src/qt/modals/about.py
Labels: Type: Bug, Type: Refactor, Type: UI/UX, Type: Translation, Priority: High

#846 Translations update from Hosted Weblate
  src/tagstudio/resources/translations/de.json
  src/tagstudio/resources/translations/es.json
  src/tagstudio/resources/translations/fil.json
  src/tagstudio/resources/translations/fr.json
  src/tagstudio/resources/translations/hu.json
  src/tagstudio/resources/translations/pt_BR.json
  src/tagstudio/resources/translations/ru.json
  src/tagstudio/resources/translations/ta.json
  src/tagstudio/resources/translations/tok.json
  src/tagstudio/resources/translations/tr.json
Labels: Type: Translation

#849 fix: catch NotImplementedError for Float16 JPEG-XL files
  src/tagstudio/qt/widgets/preview/preview_thumb.py
  src/tagstudio/qt/widgets/thumb_renderer.py
Labels: Type: Bug, Type: UI/UX, Priority: Medium

#839 fix: log all problems in translation test
  tests/test_translations.py
Labels: Type: Enhancement, Type: Tests, Type: Translation, Priority: Low

#852 Translations update from Hosted Weblate
  src/tagstudio/resources/translations/da.json
  src/tagstudio/resources/translations/es.json
  src/tagstudio/resources/translations/fr.json
  src/tagstudio/resources/translations/tok.json
  src/tagstudio/resources/translations/tr.json
Labels: Type: Translation

#845 refactor: split translation keys for about screen
  src/tagstudio/qt/modals/about.py
  src/tagstudio/resources/translations/de.json
  src/tagstudio/resources/translations/en.json
  src/tagstudio/resources/translations/es.json
  src/tagstudio/resources/translations/fil.json
  src/tagstudio/resources/translations/fr.json
  src/tagstudio/resources/translations/hu.json
  src/tagstudio/resources/translations/pl.json
  src/tagstudio/resources/translations/pt_BR.json
  src/tagstudio/resources/translations/ru.json
  src/tagstudio/resources/translations/ta.json
  src/tagstudio/resources/translations/tok.json
  src/tagstudio/resources/translations/tr.json
  src/tagstudio/resources/translations/zh_Hant.json
Labels: Type: Bug, Type: Refactor, Type: Translation, Priority: High

#840 fix(ffmpeg): remove redundant log statement
  src/tagstudio/qt/modals/ffmpeg_checker.py
Labels: Type: Bug, Priority: Low, Status: Mergeable

#841 feat: add setting to not display full file path
  src/tagstudio/core/enums.py
  src/tagstudio/qt/modals/settings_panel.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/widgets/preview/file_attributes.py
  src/tagstudio/resources/translations/en.json
  tests/qt/test_file_path_options.py
Labels: Type: Enhancement, Type: UI/UX, Priority: Low

#857 Translations update from Hosted Weblate
  src/tagstudio/resources/translations/fr.json
  src/tagstudio/resources/translations/hu.json
  src/tagstudio/resources/translations/pt_BR.json
  src/tagstudio/resources/translations/tr.json
Labels: Type: Translation

#867 feat(ci): development tooling refresh and split documentation
  .envrc.recommended
  .pre-commit-config.yaml
  contrib/.envrc-nix
  contrib/.envrc-uv
  contrib/.vscode/launch.json
  docs/develop.md
  docs/install.md
  docs/usage.md
  flake.nix
  mkdocs.yml
  nix/shell.nix
  pyproject.toml
  src/tagstudio/qt/modals/about.py
Labels: Type: Documentation, Type: Refactor, Type: CI, Status: Mergeable

#868 fix(nix/package): account for GTK platform
  nix/package/default.nix
Labels: Type: Bug, Type: Installation, Status: Mergeable, System: Linux

#869 fix(ts_qt): do not set palette for Linux-like systems that offer theming
  src/tagstudio/qt/ts_qt.py
Labels: Type: Bug, Type: Installation, Type: UI/UX, Status: Mergeable, System: Linux

#870 feat(resources): provide desktop file
  nix/package/default.nix
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/resources/tagstudio.desktop
Labels: Type: Bug, Type: QoL, Type: Installation, Priority: Medium, Status: Mergeable, System: Linux

#872 fix(flake): remove pinned input, only consume in Nix shell
  flake.lock
  flake.nix
  nix/shell.nix
Labels: Type: Bug, Type: Installation, Status: Mergeable, System: Linux

#879 Docs maintenance pass
  docs/develop.md
  docs/library/entry.md
  docs/library/field.md
  docs/library/library_search.md
  docs/library/tag.md
  docs/library/tag_categories.md
  docs/library/tag_color.md
  docs/updates/roadmap.md
  docs/updates/schema_changes.md
  docs/usage.md
  docs/utilities/macro.md
Labels: Type: Bug, Type: Documentation

#855 fix: stop ffmpeg cmd windows, refactor ffmpeg_checker
  src/tagstudio/qt/helpers/file_tester.py
  src/tagstudio/qt/helpers/silent_popen.py
  src/tagstudio/qt/helpers/vendored/ffmpeg.py
  src/tagstudio/qt/modals/about.py
  src/tagstudio/qt/modals/ffmpeg_checker.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/resources/translations/en.json
Labels: Type: Bug, Type: Refactor, Type: UI/UX, Priority: Medium, Status: Mergeable

#856 fix: hide mnemonics on macOS
  src/tagstudio/qt/translations.py
Labels: Type: Bug, Type: UI/UX, Type: Translation, Priority: Medium, Status: Mergeable

#877 fix: use UNION instead of UNION ALL
  src/tagstudio/core/library/alchemy/library.py
  src/tagstudio/core/library/alchemy/visitors.py
Labels: Priority: Critical, TagStudio: Library, TagStudio: Tags

#876 [Refactor] type fixes and minor improvements to file_opener.py
  src/tagstudio/qt/helpers/file_opener.py
Labels: Type: Refactor, Priority: Low

#884 Translations update from Hosted Weblate
  src/tagstudio/resources/translations/es.json
  src/tagstudio/resources/translations/fr.json
  src/tagstudio/resources/translations/hu.json
  src/tagstudio/resources/translations/tok.json
Labels: Type: Translation

#859 feat: settings menu
  docs/updates/roadmap.md
  pyproject.toml
  src/tagstudio/core/driver.py
  src/tagstudio/core/enums.py
  src/tagstudio/core/global_settings.py
  src/tagstudio/core/library/alchemy/enums.py
  src/tagstudio/core/utils/dupe_files.py
  src/tagstudio/main.py
  src/tagstudio/qt/cache_manager.py
  src/tagstudio/qt/modals/settings_panel.py
  src/tagstudio/qt/modals/tag_search.py
  src/tagstudio/qt/translations.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/widgets/item_thumb.py
  src/tagstudio/qt/widgets/preview/file_attributes.py
  src/tagstudio/qt/widgets/tag_box.py
  src/tagstudio/qt/widgets/video_player.py
  src/tagstudio/resources/translations/de.json
  src/tagstudio/resources/translations/en.json
  tests/conftest.py
  tests/macros/test_missing_files.py
  tests/qt/test_file_path_options.py
  tests/qt/test_global_settings.py
  tests/qt/test_qt_driver.py
  tests/test_driver.py
  tests/test_library.py
  tests/test_search.py
Labels: Type: Enhancement, Type: Refactor, Type: UI/UX, Priority: High

#885 fix: remove unescaped ampersand from "about.description"
  src/tagstudio/resources/translations/de.json
  src/tagstudio/resources/translations/en.json
Labels: Type: Bug, Type: Translation

#896 docs: update Thumb Renderer source
  CONTRIBUTING.md
Labels: Type: Documentation, Status: Mergeable

#893 fix: Prevent Dangling File Handle
  src/tagstudio/qt/widgets/thumb_renderer.py
Labels: Type: File System, System: Windows

#894 feat: improve responsiveness of GIF entries
  src/tagstudio/qt/widgets/preview/preview_thumb.py
Labels: Type: UI/UX, Priority: High, Type: Performance

#895 build: Minor improvements to PyInstaller.
  tagstudio.spec
Labels: Type: Refactor, Type: Installation

#805 feat: merge media controls.
  src/tagstudio/core/global_settings.py
  src/tagstudio/qt/helpers/qslider_wrapper.py
  src/tagstudio/qt/widgets/media_player.py
  src/tagstudio/qt/widgets/preview/preview_thumb.py
  src/tagstudio/qt/widgets/preview_panel.py
  src/tagstudio/qt/widgets/video_player.py
  src/tagstudio/resources/translations/en.json
Labels: Type: Enhancement, Type: Refactor, Type: UI/UX

#881 ui: recent libraries list improvements
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/resources/translations/en.json
Labels: Type: QoL, Type: UI/UX, Priority: Low

#882 feat(ui): add more default icons and file type equivalencies
  src/tagstudio/core/media_types.py
  src/tagstudio/qt/resources.json
  src/tagstudio/qt/widgets/preview/preview_thumb.py
  src/tagstudio/qt/widgets/thumb_renderer.py
  src/tagstudio/resources/qt/images/file_icons/archive.png
  src/tagstudio/resources/qt/images/file_icons/database.png
  src/tagstudio/resources/qt/images/file_icons/ebook.png
  src/tagstudio/resources/qt/images/file_icons/shader.png
  src/tagstudio/resources/qt/images/file_icons/shortcut.png
Labels: Type: QoL, Type: UI/UX, Priority: Low, Status: Mergeable, TagStudio: Search

#901 Minor type fixes
  src/tagstudio/qt/helpers/color_overlay.py
  src/tagstudio/qt/helpers/gradient.py
  src/tagstudio/qt/helpers/text_wrapper.py
  src/tagstudio/qt/widgets/fields.py
Labels: Type: Refactor

#880 [Refactor] Type fixes and minor improvements to flowlayout.py
  src/tagstudio/qt/flowlayout.py
Labels: Type: Refactor, Priority: Low

#902 fix(ui): seamlessly loop videos
  src/tagstudio/qt/widgets/media_player.py
Labels: Type: Bug, Type: QoL, Type: UI/UX, Priority: Medium
