Repository TagStudioDev/TagStudio, pull requests merged in 2025-05, with the labels that each got.

#904 feat: add date_format and hour_format settings
  src/tagstudio/core/global_settings.py
  src/tagstudio/qt/modals/settings_panel.py
  src/tagstudio/qt/widgets/preview/file_attributes.py
  src/tagstudio/resources/translations/en.json
  src/tagstudio/resources/translations/es.json
  tests/qt/test_global_settings.py
Labels: Type: Enhancement, Type: UI/UX, Type: Translations, Status: Mergeable

#921 feat: temporary modal to edit datetime fields and small refactors
  src/tagstudio/qt/widgets/preview/field_containers.py
Labels: Type: Refactor, Type: UI/UX

#926 feat: datetime fields settings integration
  src/tagstudio/core/global_settings.py
  src/tagstudio/qt/widgets/preview/field_containers.py
  src/tagstudio/qt/widgets/preview/file_attributes.py
Labels: Type: Enhancement, Type: Refactor, Type: UI/UX

#906 [Refactor] type fixes and minor improvements to preview_thumb.py
  src/tagstudio/qt/resources.json
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/widgets/media_player.py
  src/tagstudio/qt/widgets/preview/preview_thumb.py
  src/tagstudio/resources/qt/videos/placeholder.mp4
Labels: Type: Refactor

#903 fix(test): Fix tests to pass on windows without disrupting other platforms
  tests/conftest.py
  tests/qt/test_file_path_options.py
  tests/qt/test_global_settings.py
  tests/test_driver.py
Labels: Type: Bug, Type: Tests, System: Windows

#886 chore(pyproject): version bumping/relaxing
  .github/workflows/ruff.yaml
  flake.nix
  nix/package/default.nix
  pyproject.toml
  src/tagstudio/qt/modals/ffmpeg_checker.py
  src/tagstudio/qt/modals/tag_color_manager.py
  src/tagstudio/qt/widgets/fields.py
  src/tagstudio/qt/widgets/migration_modal.py
  src/tagstudio/qt/widgets/panel.py
  src/tagstudio/qt/widgets/preview/field_containers.py
  src/tagstudio/qt/widgets/preview/file_attributes.py
  src/tagstudio/qt/widgets/progress.py
  src/tagstudio/qt/widgets/text_line_edit.py
  src/tagstudio/qt/widgets/thumb_renderer.py
  tests/fixtures/sample.epub
  tests/fixtures/sample.ods
  tests/fixtures/sample.odt
  tests/fixtures/sample.pdf
  tests/fixtures/sample.svg
  tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.epub-_epub_cover].png
  tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.ods-_open_doc_thumb].png
  tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.odt-_open_doc_thumb].png
  tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.pdf-thumbnailer3].png
  tests/qt/__snapshots__/test_thumb_renderer/test_preview_render[sample.svg-thumbnailer4].png
  tests/qt/test_file_path_options.py
  tests/qt/test_thumb_renderer.py
Labels: Type: Refactor, Type: CI

#928 fix: tests were overwriting the settings.toml
  src/tagstudio/core/global_settings.py
Labels: Type: Bug, Type: Tests, Priority: Medium

#917 fix(nix/package): override PySide6 if later version is being used
  flake.lock
  flake.nix
  nix/package/default.nix
  nix/package/shiboken6-fix-include-qt-headers.patch
Labels: Type: Installation, Priority: High, Status: Mergeable, System: Linux
