Repository TagStudioDev/TagStudio, pull requests merged in 2025-06, with the labels that each got.

#941 feat: Press enter when adding fields
  src/tagstudio/qt/modals/add_field.py
Labels: Type: QoL, Status: Mergeable

#940 fix: add parent tags to `folders_to_tags` macro and start tagging at root folder
  src/tagstudio/qt/modals/folders_to_tags.py
  tests/qt/__snapshots__/test_folders_to_tags.ambr
Labels: Type: Bug, TagStudio: Library

#935 refactor: split QtDriver into View and Controller to follow MVC model
  pyproject.toml
  src/tagstudio/qt/main_window.py
  src/tagstudio/qt/modals/folders_to_tags.py
  src/tagstudio/qt/modals/mirror_entities.py
  src/tagstudio/qt/modals/settings_panel.py
  src/tagstudio/qt/modals/tag_color_manager.py
  src/tagstudio/qt/modals/tag_search.py
  src/tagstudio/qt/ts_qt.py
  src/tagstudio/qt/widgets/item_thumb.py
  src/tagstudio/qt/widgets/tag_box.py
  tests/conftest.py
  tests/qt/test_file_path_options.py
Labels: Type: Refactor, Status: Mergeable

#945 feat: Option to change tag click behaviour
  src/tagstudio/core/enums.py
  src/tagstudio/core/global_settings.py
  src/tagstudio/core/library/alchemy/enums.py
  src/tagstudio/qt/modals/settings_panel.py
  src/tagstudio/qt/widgets/tag.py
  src/tagstudio/qt/widgets/tag_box.py
  src/tagstudio/resources/translations/de.json
  src/tagstudio/resources/translations/en.json
Labels: Type: Enhancement, Type: UI/UX, Status: Mergeable

#958 refactor: resource_manager.py
  src/tagstudio/qt/resource_manager.py
Labels: Type: Refactor, Status: Mergeable
